redditclone/accounts/urls.py
from django.conf.urls import url
from . import views

app_name = 'accounts'

urlpatterns = [
    # name=signup/login is a easier way to refernence the url, used in signup/login.html
    url(r'^signup/', views.signup, name='signup'),
    url(r'^login/', views.loginview, name='login'),
    url(r'^logout/', views.logoutview, name='logout'),
]

redditclone/posts/urls.py
from django.conf.urls import url
from . import views

app_name = 'posts'

urlpatterns = [
    # name=create is a easier way to refernence the url, used in create.html
    url(r'^create/', views.create, name='create'),
    # the [0-9] makes sure its only int and not special char. for function also this goes to the views in posts holding the function
    url(r'^(?P<pk>[0-9]+)/upvote', views.upvote, name='upvote'),
    url(r'^(?P<pk>[0-9]+)/downvote', views.downvote, name='downvote'),
    # this is linking the views userposts 
    url(r'^user/(?P<pk>[0-9]+)', views.userposts, name='userposts'),
]

redditclone/redditclone/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from posts import views


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # the include will route to the urls.p file in accounts also used when adding new apps; links them all together
    url(r'^accounts/', include('accounts.urls')),
    url(r'^posts/', include('posts.urls')),
    # this line of code was made to have the home page be linked with the post apps, thats why we imported the ports views
    url(r'^$', views.home, name="home"),
]

redditclone/accounts/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

redditclone/posts/models.py
from __future__ import unicode_literals
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=200)
    url = models.TextField()
    pub_date = models.DateTimeField()
    author = models.ForeignKey(User)
    # default is setting a nuber to start off at or what is in the ()
    votes_total = models.IntegerField(default=1)

    # function month_date is being used to make our pub_date in models to display the way we want it.
    def month_date(self):
        # strftime in python allows us to make time a readible for humans.
        return self.pub_date.strftime('%b %e %Y')

redditclone/accounts/views.py
from django.shortcuts import render, redirect
# the import below is from django auth same as line 8,4
from django.contrib.auth.models import User
# gives us a login auth also does not allow for admin privliges
from django.contrib.auth import authenticate, login, logout

# Create your views here.
def signup(request):
    if request.method == 'POST':
        # this is checking of the password & confirm password match
        if request.POST['password1'] == request.POST['password2']:
            # try is checking if there is a username already exists if not it will run except
            try:
                user = User.objects.get(username=request.POST['username'])
                return render(request,'accounts/signup.html', {'error':'Username has already been taken'} )
            except User.DoesNotExist:
        # the request.POST[''] is comming from the name given in the form in signup.html
                user = User.objects.create_user(request.POST['username'], password=request.POST['password1'])
                # login(request, user) is from django auth
                login(request, user)
                return render(request, 'accounts/signup.html')
        else:
            # the \' allows there to be an apposterfee without messing up the quotes
            return render(request,'accounts/signup.html', {'error':'Passwords didn\'t match'} )
    else:
        return render(request, 'accounts/signup.html')
# with login validation in django have a diff name cause it wont know what function to run, like in line 34
def loginview(request):
    if request.method == 'POST':
        # this authenticates the login info
        user = authenticate(username = request.POST['username'], password = request.POST['password'])
        if user is not None:
            # a function with login
            login(request, user)
            # the 1st if is checking if there is a next
            # this is related to the login.html if request.GET.next
            if 'next' in request.POST:
                return redirect (request.POST['next'])
            return redirect('/')
        else:
            return render(request,'accounts/login.html', {'error':'The Username and Passwords didn\'t match'} )
    else:
        return render(request, 'accounts/login.html')

# this fxn will enable the logout
def logoutview(request):
    if request.method == 'POST':
        logout(request)
        return redirect('/')

redditclone/posts/views.py
from django.shortcuts import render, redirect
# this is coming from django auth same w/ line 6
from django.contrib.auth.decorators import login_required
# need to import this for the timezone
from django.utils import timezone
from .models import Post
from django.contrib.auth.models import User

# Create your views here.
@login_required
# this is the forms action in create.html
def create(request):
    # checking if == post then if it is it will run the function
    if request.method == 'POST':
        if request.POST['title'] and request.POST['url']:
            post = Post()
            post.title = request.POST['title']
            # this is allowing for links without the http to be added to it so if there isnt it wont throw an error
            if request.POST['url'].startswith('http://') or request.POST['url'].startswith('https://'):
                post.url = request.POST['url']
            else:
                post.url = 'http://' + request.POST['url']
            post.pub_date = timezone.datetime.now()
            # line below is refering to the ForeignKey
            post.author = request.user
            # saving the post with save() fxn
            post.save()
            return redirect('home')
        else:
            return render(request, 'posts/create.html', {'error':'ERROR: You must include a title and a URL to create a post.'})
    else:
        return render(request, 'posts/create.html')

# this fxn shows the posts
def home(request):
    # this is grabbing from the post models and ordering by the votes_total w/ descending order
    posts = Post.objects.order_by('-votes_total')
    return render(request, 'posts/home.html', {'posts':posts})

# fxn adds the votes
def upvote(request, pk):
    if request.method == 'POST':
        # having pk=pk is due to it constantly changing and we dont want it to be hard coded.
        post = Post.objects.get(pk=pk)
        # when it is clicked it will add 1
        post.votes_total += 1
        # saves what is being added
        post.save()
        return redirect('/')
# fxn adds the votes
def downvote(request, pk):
    if request.method == 'POST':
        # having pk=pk is due to it constantly changing and we dont want it to be hard coded.
        post = Post.objects.get(pk=pk)
        # when it is clicked it will add 1
        post.votes_total -= 1
        # saves what is being added
        post.save()
        return redirect('/')

# this fxn allows you to click a author and view all their posts
def userposts(request, pk):
    posts = Post.objects.filter(author__id=pk).order_by('-votes_total')
    author = User.objects.get(pk=pk)
    return render(request, 'posts/userposts.html', {'posts':posts, 'author':author})

redditclone/accounts/templates/accounts/login.html
<!DOCTYPE html>
<html>
<!-- this allow there to be a connected html file that applies for all of them -->
{% extends 'base.html' %}
{% block content %}
    <head>
        <meta charset="utf-8">
        <title></title>
    </head>
    <body>
        <h1>Login</h1>
    <!-- this is beingv used to show errors -->
    {% if error %}
    {{ error }}
    <br>
    <!-- added another break cause there wasn't enough space btwn the error message and the form -->
    <br>
    {% endif %}

        <!--  url 'accounts:login'  is refering to the urls.py name of the new app with the code of line 4 in accounts/urls.py for the route -->
        <!-- form is sending info to the database using post  -->
        <form class="" action="{% url 'accounts:login' %}" method="post">
            <!-- this line of code allows us to submit/use the form -->
            {% csrf_token %}

        {% if request.GET.next %}
            <input type="hidden" name="next" value={{ request.GET.next }}>
        {% endif %}

            Username:
            <br>
            <input type="text" name="username">
            <br>
            Password:
            <br>
            <input type="password" name="password">
            <br>
            <br>
            <input class="btn btn-primary" type="submit" value="Login">
        </form>
    </body>
    {% endblock %}
</html>

redditclone/accounts/templates/accounts/signup.html
<!DOCTYPE html>
<html>
<!-- this allow there to be a connected html file that applies for all of them -->
{% extends 'base.html' %}
{% block content %}
    <head>
        <meta charset="utf-8">
        <title></title>
    </head>
    <body>
        <h1>Sign Up!</h1>
    <!-- this is beingv used to show errors -->
    {% if error %}
    {{ error }}
    <br>
    <!-- added another break cause there wasn't enough space btwn the error message and the form -->
    <br>
    {% endif %}

        <!--  url 'signup'  is refering to the urls.py name for the route -->
        <!-- form is sending info to the database using post  -->
        <form class="" action="{% url 'accounts:signup' %}" method="post">
            <!-- this line of code allows us to submit/use the form -->
            {% csrf_token %}
            Username:
            <br>
            <input type="text" name="username">
            <br>
            Password:
            <br>
            <input type="password" name="password1">
            <br>
            Confirm Password:
            <br>
            <input type="password" name="password2" >
            <br>
            <br>
            <input class="btn btn-primary" type="submit" value="Sign Up!">
        </form>
    </body>
    {% endblock %}
</html>

redditclone/posts/templates/posts/create.html
<!DOCTYPE html>
<html>
<!-- this allow there to be a connected html file that applies for all of them -->
{% extends 'base.html' %}
{% block content %}
    <head>
        <meta charset="utf-8">
        <title></title>
    </head>
    <body>
        <h1>New Post</h1>
    <!-- this is being used to show errors -->
    {% if error %}
    {{ error }}
    <br>
    <!-- added another break cause there wasn't enough space btwn the error message and the form -->
    <br>
    {% endif %}

        <!--  url 'posts:create'  is refering to the urls.py name of the new app with the code of line 4 in posts/urls.py for the route -->
        <!-- form is sending info to the database using post  -->
        <!-- will be sent to views.py create fxn -->
        <form class="" action="{% url 'posts:create' %}" method="post">
            <!-- this line of code allows us to submit/use the form -->
            {% csrf_token %}

            Title:
            <br>
            <input type="text" name="title">
            <br>
            URL:
            <br>
            <input type="text" name="url">
            <br>
            <br>
            <input class="btn btn-primary" type="submit" value="Post">
        </form>
    </body>
    {% endblock %}
</html>

redditclone/posts/templates/posts/home.html
<!DOCTYPE html>
<html>
<!-- this allow there to be a connected html file that applies for all of them -->
{% extends 'base.html' %} {% block content %}

<head>
    <meta charset="utf-8">
    <title>Home</title>
</head>

<body>
    <h1>The homepage of nowhere</h1>
    <!-- gets access to the posts app create fxn -->
    <a class="btn btn-primary" href="{% url 'posts:create' %}">New Post</a>
    <br>
    <br>
    <!-- a loop to print out the posts -->
    {% for post in posts.all %}
    <table>
        <tr>
            <!-- the span syntax is comming from bootstrap -->
            <!-- used some javascript to use the logout, so what it is saying is when it is clicked it will run the form which is related by the id. also made the form hidden so would not show up -->
            <td style="padding-right: 20px;"><a href="#" onClick="document.getElementById('upvote{{ post.id }}').submit()"><span class="glyphicon glyphicon-menu-up" aria-hidden="true"></span></a><br> {{ post.votes_total }}<br><a href="#" onClick="document.getElementById('downvote{{ post.id }}').submit()"><span class="glyphicon glyphicon-menu-down" aria-hidden="true"></span></a></td>
            <td><a href="{{ post.url }}">{{ post.title }}</a><br>
                <!-- these two print out the date and who posted it  -->
                <!-- 'posts:userposts' post.author.id is with the views fxn -->
                {{ post.month_date }} by <a href="{% url 'posts:userposts' post.author.id %}">{{ post.author.username }}</a></td>
        </tr>

        <br>
    </table>
    <!--  url 'posts:upvote'  is refering to the urls.py name of the app with the code of line 4 in posts/urls.py for the route also with the id of the post -->
    <!-- form is sending info to the database using post  -->
    <!-- will be sent to views.py upvote fxn -->
    <form id="upvote{{ post.id }}" action="{% url 'posts:upvote' post.id %}" method="post">
        {% csrf_token %}
        <input type="hidden">
    </form>
    <!--  url 'posts:downvote'  is refering to the urls.py name of the app with the code of line 4 in posts/urls.py for the route also with the id of the post -->
    <!-- form is sending info to the database using post  -->
    <!-- will be sent to views.py downvote fxn -->
    <form id="downvote{{ post.id }}" action="{% url 'posts:downvote' post.id %}" method="post">
        {% csrf_token %}
        <input type="hidden">
    </form>

    {% endfor %}

</body>
{% endblock %}

</html>

redditclone/posts/templates/posts/userposts.html
<!DOCTYPE html>
<html>
<!-- this allow there to be a connected html file that applies for all of them -->
{% extends 'base.html' %} {% block content %}

<head>
    <meta charset="utf-8">
    <title>Home</title>
</head>

<body>
    <h1>All Posts by {{ author.username }} </h1>
    <!-- a loop to print out the posts -->
    {% for post in posts.all %}
    <table>
        <tr>
            <!-- the span syntax is comming from bootstrap -->
            <!-- used some javascript to use the logout, so what it is saying is when it is clicked it will run the form which is related by the id. also made the form hidden so would not show up -->
            <td style="padding-right: 20px;"><a href="#" onClick="document.getElementById('upvote{{ post.id }}').submit()"><span class="glyphicon glyphicon-menu-up" aria-hidden="true"></span></a><br> {{ post.votes_total }}<br><a href="#" onClick="document.getElementById('downvote{{ post.id }}').submit()"><span class="glyphicon glyphicon-menu-down" aria-hidden="true"></span></a></td>
            <td><a href="{{ post.url }}">{{ post.title }}</a><br>
                <!-- these two print out the date and who posted it  -->
                <!-- 'posts:userposts' post.author.id is with the views fxn -->
                {{ post.month_date }} by <a href="{% url 'posts:userposts' post.author.id %}">{{ post.author.username }}</a></td>
        </tr>

        <br>
    </table>
    <!--  url 'posts:upvote'  is refering to the urls.py name of the app with the code of line 4 in posts/urls.py for the route also with the id of the post -->
    <!-- form is sending info to the database using post  -->
    <!-- will be sent to views.py upvote fxn -->
    <form id="upvote{{ post.id }}" action="{% url 'posts:upvote' post.id %}" method="post">
        {% csrf_token %}
        <input type="hidden">
    </form>
    <!--  url 'posts:downvote'  is refering to the urls.py name of the app with the code of line 4 in posts/urls.py for the route also with the id of the post -->
    <!-- form is sending info to the database using post  -->
    <!-- will be sent to views.py downvote fxn -->
    <form id="downvote{{ post.id }}" action="{% url 'posts:downvote' post.id %}" method="post">
        {% csrf_token %}
        <input type="hidden">
    </form>

    {% endfor %}

</body>
{% endblock %}

</html>

redditclone/templates/base.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Reddit Clone</title>
    <!-- bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <!-- jQuery nessasary for bootstraps javascript plugins -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- put in additional compiled plugins or other individual files -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

</head>

<body>
<!-- bootstrap only works if you have the above script tags -->
<!-- look at doc to find diff ways to modify in bootstrap -->
    <nav class="navbar navbar-inverse">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#mynav">
        <!-- span displays how many lines will be shown in button, have 3 cause it is standard for a button(hamburger) in dashboard -->
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <!-- the link is being routed from the url pattern and going to home is th ename given for the url -->
                <a class="navbar-brand" href="{% url 'home' %}">Reddit Clone </a>
            </div>
            <div class="collapse navbar-collapse" id="mynav">
                <ul class="nav navbar-nav navbar-right">
                    <!-- this is checking if the user is authentic -->
                    {% if user.is_authenticated %}
                    <!-- used some javascript to use the logout, so what it is saying is when it is clicked it will run the form which is related by the id. also made the form hidden so would not show up -->
                    <li><a href="#" onClick="document.getElementById('logout').submit()">Logout</a></li>
                    <form id="logout"class="" action="{% url 'accounts:logout' %}" method="post">
                        {% csrf_token %}
                        <input type="hidden">
                    </form>
                    {% else %}
                    <!-- says go to the url accounts/signup -->
                    <li><a href="{% url 'accounts:signup' %}">Signup</a></li>
                    <li><a href="{% url 'accounts:login' %}">Login</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>

<div class="container">
    <!-- having an outide templates folder allows the ability for an html to affect all the files. So with a change/make it will affect all the html files and not have to go indiviually to each html file. Also make sure to connect in settings.py with the templates/dir[] section -->
    {% block content %}
    {% endblock %}

</div>

</body>

</html>